# permissions for end users to edit macbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: macbook-editor-role
rules:
- apiGroups:
  - mock.dong.com
  resources:
  - macbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mock.dong.com
  resources:
  - macbooks/status
  verbs:
  - get
