# permissions for end users to view macbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: macbook-viewer-role
rules:
- apiGroups:
  - mock.dong.com
  resources:
  - macbooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mock.dong.com
  resources:
  - macbooks/status
  verbs:
  - get
