
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mock.dong.com
  resources:
  - macbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mock.dong.com
  resources:
  - macbooks/finalizers
  verbs:
  - update
- apiGroups:
  - mock.dong.com
  resources:
  - macbooks/status
  verbs:
  - get
  - patch
  - update
